[kobo]
default_token = "c710cac4d6d5fafbda973f04b30a2c27bda914c4"          # <- token akun Kobo Anda, dipakai untuk SEMUA AP
default_login_uid = "..."                        # fallback kalau pilih "(Manual)" di dropdown
default_register_uid = "..."

[kobo.ap.AP-Surabaya]
login_uid = "aE3xS8zXQsU9KQsiT9T7PA"       # Asset UID form Login khusus Surabaya
register_uid = "aRVadKAkpz2PYMaZH2gXKU"    # Asset UID form Register khusus Surabaya

[kobo.ap."AP-Kalimantan Barat"]
login_uid = "..."
register_uid = "..."
